### ISSUE TITLE
 How to automatically get topic and Message type

### ISSUE THREAD

**Issue by Max-Cheng** [fetchrobotics/rosgo#23]
I want to auto creat Subscriber to read all ROS message, but example didn't show this

**Comment by cjds** [comment]
Hey Max, could you be more specific about what you are trying.

Go, like C++ cannot arbitrarily read a message that it doesn't know about. Could you make a small pseudocode example of what you are trying to do and what the exact problem is?

**Comment by justinscorringe** [comment]
You could probably use rosout or rosgraph_msgs/Log ?

**Comment by justinscorringe** [comment]
Generate these in your code
```
//go:generate gengo msg std_msgs/Header
//go:generate gengo msg rosgraph_msgs/Log
```
```
func callback(msg *rosgraph_msgs.Log) {
	fmt.Printf("Node: %s\n", msg.Name)
	for i := 1; i<(len(msg.Topics)); i++ {
	fmt.Printf("Topics: %s\n", msg.Topics[i])
	}
}
```

This callback will print a list of Nodes and their topics, probably a way to get their type as well

**Comment by Max-Cheng** [comment]
I got a stupid solution. Using bash to get all message type and use bash to generate code. Ours project is using golang to sent message to webviz to make auto-drive engineer more convenient ros system.

**Comment by justinscorringe** [comment]
Ah nice. I wonder if its possible to get bash to show a topics message type?

**Comment by Max-Cheng** [comment]
Try this

func Gettopic() map[string]string {
	Topic := make(map[string]string, 0)
	index := 0
	out, _ := Exec_shell("rostopic list")
	for i, v := range out {
		if v == '\n' {
			Topic[out[index:i]] = ""
			index = i + 1
		}
	}
	for i := range Topic {
		Topic[i], _ = Exec_shell("rostopic type " + i[1:])
	}
	return Topic
}


func Exec_shell(s string) (string, error) {
	cmd := exec.Command("/bin/bash", "-c", s)
	var out bytes.Buffer
	cmd.Stdout = &out
	err := cmd.Run()
	return out.String(), err
}

**Comment by justinscorringe** [comment]
Looks good. I think I will try to modify the XML-RPC of this package first to parse a getTopicTypes request to the ros master first. Then I don't need to ssh bash access on the ros system since I am doing mine remotely.

**Comment by justinscorringe** [comment]
Didn't need to modify anything!

Ran this command, you can omit the first two values,
the result of the values returned are pairs of topic and message type

xmlrpc.Call("http://127.0.0.1:11311", "getTopicTypes", "listener")

**Comment by Max-Cheng** [comment]
One more things ,you need to auto generate code to your project, and my job is sent ros message to clients. So maybe it’s different

**Comment by Max-Cheng** [comment]
But good job! You did this!

**Comment by justinscorringe** [comment]
Heres another headscratcher I'm struggling with. Say I subscribe to a topic, usually I know the info I want to parse from it. But lets say I've used a function to subscribe to a topic, based on the topic and message type returned on the gettopictypes xml. It will subscribe successfully as the info is all correct. But If I want the code to display all info from that message to stdout, without me asking for any property of it in particular, is that possible? Like to display all of geometry_msgs/Twist, which is two structs with 3 values each inside. As a user I can usually ask for each property specifically like linear.x, but the code needs to print it all and work for any message type. I wonder if thats possible?  Something like rostopic echo

**Comment by Max-Cheng** [comment]
You need to custome gengo. Try to custom Gengo.

**Comment by justinscorringe** [comment]
Solution I wanted was so stupidly easy. Just parse msg value alone as callback..
```
func callback(msg *geometry_msgs.Twist) {
	fmt.Printf("%v\n", msg)
}
```

**Comment by Max-Cheng** [comment]
You should run demo first.😄

**Comment by justinscorringe** [comment]
I had to go quite far to get this all going without message definitions. Need to run wildcard "*" subscription on topics and retrieve it through the TCP response header, and run gengo on the output.

**Comment by Max-Cheng** [comment]
It sounds like your program is only for a single ros environment.
