### ISSUE TITLE
Problems with generating larger messages

### ISSUE THREAD

**Issue by justinscorringe** [fetchrobotics/rosgo#26]
Hi. Its awesome to see this package being maintained!
I have a question I've asked on akio master but may get more attention here
I have no problem subscribing and publishing standard message types, however 
if I generated geometry_msgs/Twist in my package for example, it will fail to build due to import cycles. The Twist.go file also imports geometry_msgs to grab its definitions.
Is there an workaround for this? Or am I going about it completely wrong?
Thank you

**Comment by pavansoundara** [comment]
We noticed the import cycles issue a while ago and fixed it in this PR https://github.com/fetchrobotics/rosgo/pull/7. 

The fix was to simply skip importing the package if field package and generated package are same.

**Comment by justinscorringe** [comment]
Awesome! Sorry for not noticing this. 
`src/github.com/fetchrobotics/rosgo/test/test_justin/vendor/geometry_msgs/Twist.go:47:10: undefined: Vector3`
Is the next problem it shows, is this user error or something you've run into?

**Comment by pavansoundara** [comment]
You will have to generate the go definitions of the messages that `geometry_msgs/Twist` depends on in addition.
```
gengo msg geometry_msgs/Twist
gengo msg geometry_msgs/Vector3
```

**Comment by justinscorringe** [comment]
Worked a charm! Thank you! 

I'm looking at implementing nodes over a network, is there a way to implement IP+PORT of a master into a go node?

**Comment by pavansoundara** [comment]
Go node will try and connect to IP+PORT set in `ROS_MASTER_URI` env variable. Setting or updating `ROS_MASTER_URI` to IP+PORT of your master node should be the way to go.

**Comment by justinscorringe** [comment]
That did the trick. Thank you for your help!

**Comment by justinscorringe** [comment]
Another quick one if you're still listening;

I realise I can run rosgo nodes on a system without ROS installed, only the message generation does not function. I have tried copying the ros/share message definition folder to this non-ros machine and setting the `ROS_PACKAGE_PATH` as I would in other packages, but gengo doesn't quite work. Are there more paths/files required for message generation or is this a limitation of the package?

**Comment by cjds** [comment]
Hey @justinscorringe  just read your message. Could you give me the exact error that `gengo` is failing with? Or open a new issue with the information and assign it to me?

**Comment by justinscorringe** [comment]
hi @cjds. It is working now thank you, I had set the ros_package_path to the root folder of share, setting it to the share folder itself worked. 

What I'd like to do is use gengo without the share folder, and properly point rosPkgPaths[] to the ros machine remotely. Is there an option for this at the moment?  For now I am retrieving definitions over local network via the tcp response headers upon subscription.
