### ISSUE TITLE
Messages with field "Type"

### ISSUE THREAD

**Issue by justinscorringe** [fetchrobotics/rosgo#29]
Some messages are generated with the field Type, but also have method Type which causes an error

here is an example;

`JoyFeedback.Type is a field, not a method`
`type JoyFeedback has both field and method named Type`

here is what it looks like in the JoyFeedback.go, NewMessage tries to reference m.Type.
(rosmsg removed for formatting)

```
type JoyFeedback struct {
	Type      uint8
	Id        uint8
	Intensity float32 
}

func (m *JoyFeedback) Type() ros.MessageType {
	return MsgJoyFeedback
}
```

As Type is a field that the ros message uses, the Type() method name should be changed in rosgo

**Comment by justinscorringe** [comment]
Seems to also be an issue with constants being re-declared by sub message types, 

```
go/src/github.com/fetchrobotics/rosgo/test/testalltopics/vendor/visualization_msgs/InteractiveMarkerUpdate.go:12:2: KEEPALIVE redeclared in this block
	previous declaration at go/src/github.com/fetchrobotics/rosgo/test/testalltopics/vendor/visualization_msgs/InteractiveMarkerFeedback.go:14:22

```

The Types problem is an easy substitution but this one might be harder. We cannot miss any constants, as you may want to interface with only the sub-message type. One solution could be to analyze constants, and if required, publish a constants file for each package for message files to reference?

**Comment by pavansoundara** [comment]
Two different messages in the same package could have a constant with the same name but with different assignments and different meanings. In such cases, this solution might not work. I think we can use the convention followed in `protoc-gen-go`, that is prefix MessageType to the constant name. 

For example:
```Go
const (
        InteractiveMarkerUpdate_KEEPALIVE uint8 = 0
        InteractiveMarkerUpdate_UPDATE    uint8 = 1
)
```

**Comment by justinscorringe** [comment]
Looks good. Would this still allow full functionality in an instance where we receive something like a diagnosticstatus msg, where we take the level byte to set the status level field?

**Comment by pavansoundara** [comment]
I think it should still allow for full functionality. You can try using gengo with the changes in https://github.com/fetchrobotics/rosgo/pull/30 to see if any of the existing functionalities are affected.

**Comment by justinscorringe** [comment]
Awesome fix thank you!
